// List of Stopwatches
export const GET_STOPWATCHED_DATA_REQUEST = 'GET_STOPWATCHED_DATA_REQUEST';
export const GET_STOPWATCHED_DATA_SUCCESS = 'GET_STOPWATCHED_DATA_SUCCESS';
export const GET_STOPWATCHED_DATA_FAIL = 'GET_STOPWATCHED_DATA_FAIL';

export const ADD_NEW_OPEN = 'ADD_NEW_OPEN';
export const ADD_NEW_CLOSE = 'ADD_NEW_CLOSE';

export const ADD_NEW_APPLY_REQUEST = 'ADD_NEW_APPLY_REQUEST';
export const ADD_NEW_APPLY_SUCCESS = 'ADD_NEW_APPLY_SUCCESS';
export const ADD_NEW_APPLY_FAIL = 'ADD_NEW_APPLY_FAIL';
export const ADD_NEW_TITLE_CHANGE = 'ADD_NEW_TITLE_CHANGE';
export const ADD_NEW_RESET_REQUEST_STATUS = 'ADD_NEW_RESET_REQUEST_STATUS';

export const SET_CURRENT = 'SET_CURRENT';

//Stopwatch item

export const DELETE_STOPWATCH_REQUEST = 'DELETE_STOPWATCH_REQUEST';
export const DELETE_STOPWATCH_SUCCESS = 'DELETE_STOPWATCH_SUCCESS';
export const DELETE_STOPWATCH_FAIL = 'DELETE_STOPWATCH_FAIL';

export const TIME_UPDATE_STOPWATCH = 'TIME_UPDATE_STOPWATCH';
export const SET_START_TIME_STOPWATCH = 'SET_START_TIME_STOPWATCH';

//Current Stopwatch

export const START_STOPWATCH = 'START_STOPWATCH';
export const STOP_STOPWATCH = 'STOP_STOPWATCH';
export const RESET_STOPWATCH = 'RESET_STOPWATCH';
//-Fixed lap
export const FIXED_LAP = 'FIXED_LAP';
export const SET_NEW_BREAKPOINT = 'SET_NEW_BREAKPOINT';
export const ADD_NEW_LAP = 'ADD_NEW_LAP';

//Laps
export const GET_LAPS_DATA_REQUEST = 'GET_LAPS_DATA_REQUEST';
export const GET_LAPS_DATA_SUCCESS = 'GET_LAPS_DATA_SUCCESS';
export const GET_LAPS_DATA_FAIL = 'GET_LAPS_DATA_FAIL';

// Other

export const RESET_REQUEST_STATUS = 'RESET_REQUEST_STATUS';

export const SAVE_ALL_STOPWATCHES_REQUEST = 'SAVE_ALL_STOPWATCHES_REQUEST';
export const SAVE_ALL_STOPWATCHES_SUCCESS = 'SAVE_ALL_STOPWATCHES_SUCCESS';
export const SAVE_ALL_STOPWATCHES_FAIL = 'SAVE_ALL_STOPWATCHES_FAIL';